name: Compare Directories

on:
  push:
    branches:
      - km-main-change
      #- main

jobs:
  Compare:
    runs-on: ubuntu-latest
    steps:
    - name: Clone dmmulroy/better-ts-errors.nvim
      run: git clone https://github.com/dmmulroy/better-ts-errors.nvim.git

    - name: Clone mattpocock/ts-error-translator repository
      run: git clone https://github.com/mattpocock/ts-error-translator.git

    - name: Set up git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    # - name: List contents of error_templates/ and errors
    #   run: |
    #     ls "better-ts-errors.nvim/error_templates"
    #     ls "ts-error-translator/packages/engine/errors"

    - name: Run diff script and create PR
      run: |
        # Define your directories and GitHub token here
        dir1="ts-error-translator/packages/engine/errors/"
        dir2="better-ts-errors.nvim/error_templates"
        github_token="${{ secrets.GITHUB_TOKEN }}"

        # Use diff to compare the directories and store the differences in a variable
        differences=$(diff -rq $dir1 $dir2 || true)

        if [ -n "$differences" ]; then
          cd better-ts-errors.nvim/
          # Create a new branch and commit the changes
          branch_name="auto-pr-$(date +”%d-%b-%Y”)"
          git checkout -b "$branch_name"
          git add -A
          git commit -m "Auto commit for directory differences"
          git push origin "$branch_name"

          # Create a new pull request using the GitHub API
          pull_request_title="Auto PR: Directory Differences"
          pull_request_body="Differences found between directories: $dir1 and $dir2\n\n$differences"
          pull_request_head="$branch_name"
          pull_request_base="main"  # Change this to your target branch

          response=$(curl -s -X POST "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls" -H "Authorization: token $github_token" -d '{
            "title": "'${pull_request_title}'",
            "body": "'${pull_request_body}'",
            "head": "'${pull_request_head}'",
            "base": "'${pull_request_base}'"
          }')
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
