name: Sync Files
on:
  push:
    branches:
      - km-main-change
      #- main <- Change before PR
  workflow_dispatch:

jobs:
  create-token:
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"

  sync-errors-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync Errors
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          sourceRepository: mattpocock/ts-error-translator
          sourceFolder: packages/engine/errors
          destinationFolder: error_templates
          destinationToke: ${{ secrets.PRIVATE_KEY }}

      - name: Create PR
        id: create_pr
        uses: EndBug/add-and-commit@v9
        with:
          default_branch: main # Change this to match your main branch
          branch_name: sync-errors-${{ github.run_id }}
          base: main # Change this to match your main branch
          author_email: test@test.com
          author_name: test
          commit_message: 'Sync Errors from ts-error-translator'

      - name: PR Created
        if: steps.create_pr.outputs.pull_request_number != ''
        run: |
          echo "PR created: ${{ steps.create_pr.outputs.pull_request_number }}"
          echo "::set-output name=pull_request_number::${{ steps.create_pr.outputs.pull_request_number }}"