name: Compare Directories

on:
  push:
    branches:
      - km-main-change
      #- main <- Change before PR

jobs:
  Compare:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout dmmulroy/better-ts-errors.nvim
      uses: actions/checkout@v3
      with:
        repository: dmmulroy/better-ts-errors.nvim
        path: error_templates/
        ref: km-main-change #main <- Change  before PR
    
    #Take out before PR
    - name: List contents of error_templates/
      run: ls error_templates/

    - name: Clone ts-error-translator repository
      run: git clone https://github.com/mattpocock/ts-error-translator.git ts-error-translator/

    - name: List contents 
      run: ls ts-error-translator/

    - name: Compare Directories
      run: bash ${GITHUB_WORKSPACE}/scripts/open_pr.sh
