name: Compare Directory

on:
  push:
    branches:
      #- main
      - km-main-change

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout better_ts_errors
      uses: actions/checkout@v3
      with:
        repository: https://github.com/dmmulroy/better-ts-errors.nvim.git
        path: error_templates
        ref: km-main-change #main <- change back to main before pushing to prod

    - name: Checkout ts-error-translator
      uses: actions/checkout@v3
      with:
        repository: https://github.com/mattpocock/ts-error-translator.git
        path: packages/engine/errors
        ref: main  

    - name: List files in the first directory
      run: |
        cd ts-error-translator/packages/engine/errors
        find . -type f

    - name: List files in the second directory
      run: |
        cd better_ts_errors/error_templates
        find . -type f

    - name: Run the diff
      run: |
        diff -r ts-error-translator/packages/engine/errors better_ts_errors/error_templates
