name: Compare Directories

on:
  push:
    branches:
      - km-main-change
      #- main

jobs:
  Compare:
    runs-on: ubuntu-latest

    steps:
    - name: Clone dmmulroy/better-ts-errors.nvim
      run: git clone https://github.com/dmmulroy/better-ts-errors.nvim.git

    - name: Clone mattpocock/ts-error-translator repository
      run: git clone https://github.com/mattpocock/ts-error-translator.git

    - name: Set up git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    # - name: List contents of error_templates/ and errors
    #   run: |
    #     ls "better-ts-errors.nvim/error_templates"
    #     ls "ts-error-translator/packages/engine/errors"

    - name: Compare Directories and Create PR
      run: |
        TITLE="Syncing error templates"
        BODY="Auto PR that's created to sync the error templates."
        BASE="main"
        dir1="ts-error-translator/packages/engine/errors/"
        dir2="better-ts-errors.nvim/error_templates"
        github_token="${{ secrets.GITHUB_TOKEN }}"

        # Use diff to compare the directories and store the differences in a variable
        differences=$(diff -rq $dir1 $dir2 || true)

        if [ -n "$differences" ]; then
            # Create the pull request
            PR_RESPONSE=$(curl -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -d '{
                    "title": "'$TITLE'",
                    "body": "'$BODY'",
                    "head": "feature-branch",
                    "base": "'$BASE'"
                }' \
                "https://api.github.com/repos/dmmulroy/better-ts-errors.nvim/pulls")

            # Add the reviewer to the PR
            REVIEWER="dmmulroy"
            curl -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -d '{
                    "reviewers": ["'"$REVIEWER"'"]
                }' \
                "https://api.github.com/repos/dmmulroy/better-ts-errors.nvim/pulls/$PR_NUMBER/requested_reviewers"
        else
            echo "No differences found in directories."
        fi
