name: Compare Directories

on:
  push:
    branches:
      - km-main-change
      #- main

jobs:
   Compare-Directories:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: km-main-change #Change back to main before PR

    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: mattpocock/ts-error-translator
        path: main

    - name: run config git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "githyub-actions"

    - name: Run diff script and create PR
      run: |
        # Define your directories and GitHub token here
        dir1="ts-error-translator/packages/engine/errors/"
        dir2="better-ts-errors.nvim/error_templates"

        # Use diff to compare the directories and store the differences in a variable
        differences=$(diff -rq $dir1 $dir2 || true)

        if [ -n "$differences" ]; then
          cd better-ts-errors.nvim/
          # Create a new branch and commit the changes
          branch_name="auto-pr-$(date +”%d-%b-%Y”)"
          git checkout -b "$branch_name"
          echo $differences > differences.patch
          git add differences.patch
          git commit -m "Auto commit for directory differences"
          git push origin "$branch_name"
        fi

    - name: Commit files
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git commit -a -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
