name: Clone Repositories and Compare Directories

on:
  push:
    branches:
      #- main
      - km-main-change

jobs:
  clone-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Clone Repository 1
        run: git clone https://github.com/mattpocock/ts-error-translator.git ts_error_translator/
        env:
          REPO_URL1: https://github.com/mattpocock/ts-error-translator.git
          DIRECTORY_NAME1: ts_error_translator

      - name: Clone Repository 2
        run: git clone https://github.com/dmmulroy/better-ts-errors.nvim.git better_ts_errors/
        env:
          REPO_URL2: https://github.com/dmmulroy/better-ts-errors.nvim.git
          DIRECTORY_NAME2: better_ts_errors

  sync-dirs:
    needs: clone-repos
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v3

      - name: Synchronize Error Directories
        run: |
          # Run the diff command
          diff -r "ts-error-translator/packages/engine/errors" "better-ts-errors.nvim/error-templates/" || true

          # Synchronize the directories using rsync
          rsync -ru "ts_error_translator/packages/config/engine/errors/" "better_ts_errors/error-templates/"
          
        env:
          DIRECTORY_NAME1: ts_error_translator
          DIRECTORY_NAME2: better_ts_errors

   create-pr:
    needs: sync-dirs
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v3

      - name: Create Pull Request
        run: |
          # Commit the changes in better_ts_errors
          git -C better_ts_errors add .
          git -C better_ts_errors commit -m "Sync with ts_error_translator"

          # Push the changes to the repository
          git -C better_ts_errors push

          # Create a pull request
          hub pull-request -m "Sync better_ts_errors with ts_error_translator" || true

        env:
          DIRECTORY_NAME1: ts_error_translator
          DIRECTORY_NAME2: better_ts_errors
