name: Compare Directories

on:
  push:
    branches:
      - km-main-change
      #- main

jobs:
   Diff-Directories:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: fregante/setup-git-user@v2

    - name: Clone Repo's
      run: |
        gh repo clone dmmulroy/better-ts-errors.nvim
        gh repo clone mattpocock/ts-error-translator
        #git clone https://github.com/mattpocock/ts-error-translator.git && git clone https://github.com/dmmulroy/better-ts-errors.nvim.git
      env:
        GH_TOKEN: ${{ github.token }}

    # - name: git config
    #   run: |
    #     git config --global user.email "kylemelvin95@gmail.com"
    #     git config --global user.name "kylemelvin95"

    # - name: ls directories
    #   run: |
    #     ls 
    #     pwd

    - name: diff the directories
      run: |
        dir1="ts-error-translator/packages/engine/errors/"
        dir2="better-ts-errors.nvim/error_templates"

        # Use diff to compare the directories and store the differences in a variable
        differences=$(diff -rq $dir1 $dir2 || true)
        echo $differences
        if [ -n "$differences" ]; then
          cd better-ts-errors.nvim/
          # Create a new branch and commit the changes
          branch_name="auto-pr-$(date +”%d-%b-%Y”)"
          git checkout -b "$branch_name"
          echo $differences > differences.patch
          git add differences.patch
          git commit -m "Auto commit for directory differences"
          git push origin "$branch_name"
        fi
      env:
        GH_TOKEN: ${{ github.token }}
      # env: 
      #   PAT_TOKEN: ${{ secrets.TOKEN }}
