name: Clone Repositories and Compare Directories

on:
  push:
    branches:
      #- main
      - km-main-change

jobs:
  clone-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Clone Repository 1
        run: git clone https://github.com/mattpocock/ts-error-translator.git ts_error_translator/

      - name: Clone Repository 2
        run: git clone https://github.com/dmmulroy/better-ts-errors.nvim.git better_ts_errors/

      - name: Archive Directories
        run: |
          tar -czf directories.tar.gz "ts_error_translator/" "better_ts_errors/"
        working-directory: ${{ github.workspace }}

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: directory-artifact
          path: directories.tar.gz

  sync-dirs:
    needs: clone-repos
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v3
      
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: directory-artifact
          path: ${{ github.workspace }}

      - name: Extract Directories
        run: |
          tar -xzf directories.tar.gz
        working-directory: ${{ github.workspace }}

      - name: Set Permissions
        run: |
          ls -lah
          pwd
          chmod -R 777 ts_error_translator/
          chmod -R 777 better_ts_errors/

      - name: Synchronize Error Directories
        run: |
          # Run the diff command
          l\s -lah
          pwd
          diff -r "better_ts_errors/error_templates" "ts_error_translator/packages/engine/errors"

          # Synchronize the directories using rsync
          #rsync -ru ts_error_translator/packages/config/engine/errors/ better_ts_errors/error_templates/

  create-pr:
    needs: sync-dirs
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v3
      
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: directory-artifact
          path: ${{ github.workspace }}      

      - name: Create Pull Request
        run: |
          # Commit the changes in better_ts_errors
          git -C better_ts_errors add .
          git -C better_ts_errors commit -m "Sync with ts_error_translator"
          git -C better_ts_errors push

          # Create a pull request
          hub pull-request -m "Sync better_ts_errors with ts_error_translator" || true

