name: Compare Directories

on:
  push:
    branches:
      - km-main-change
      #- main <- Change before PR

jobs:
  Compare:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout dmmulroy/better-ts-errors.nvim
      run: git clone https://github.com/dmmulroy/better-ts-errors.nvim.git better-ts-errors.nvim/

    - name: Clone ts-error-translator repository
      run: git clone https://github.com/mattpocock/ts-error-translator.git ts-error-translator/

    - name: List contents 
      run: ls -la ${GITHUB_WORKSPACE}
    
    - name: get path
      run: pwd

    # - name: Compare Directories
    #   run: |
    #     chmod +x ${GITHUB_WORKSPACE}/scripts/open_pr.sh
    #     #./${GITHUB_WORKSPACE}/scripts/open_pr.sh
