name: Compare Directories

on:
  push:
    branches:
      - km-main-change
      #- main

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dmmulroy/better-ts-errors.nvim
      uses: actions/checkout@v3
      with:
        repository: dmmulroy/better-ts-errors.nvim
        path: error_templates
        ref: km-main-change #main <- change back before push to prod

    - name: Checkout mattpocock/ts-error-translator
      uses: actions/checkout@v3
      with:
        repository: mattpocock/ts-error-translator
        path: ts-error-translator/packages/engine/errors
        ref: main

    - name: List files in repository 1
      run: |
        cd error_templates
        find . -type f

    - name: List files in repository 2
      run: |
        cd ts-error-translator/packages/engine/errors
        find . -type f

    - name: Run the diff
      run: |
        diff -r error_templates/ ts-error-translator/packages/engine/errors
