name: Sync Files
on:
  push:
    branches:
      - km-main-change
      #- main <- Change before PR
  workflow_dispatch:

jobs:     
  sync-errors-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync Errors
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_INSTALLATION_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Sync Error Templates'
          branch: sync-error-templates
          base: main  # Replace with your desired base branch
          body: 'Synced error_templates from ts-error-translator.'
          commit-message: 'Sync error_templates'
          delete-branch: true

      - name: PR Created
        if: steps.create_pr.outputs.pull_request_number != ''
        run: |
          echo "PR created: ${{ steps.create_pr.outputs.pull_request_number }}"
          echo "::set-output name=pull_request_number::${{ steps.create_pr.outputs.pull_request_number }}"