name: Check TS Errors and Open PR

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: #Manual trigger 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Run shell commands
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
	  git clone https://github.com/mattpocock/ts-error-translator.git
	  pwd
	  
