name: Compare Directories

on:
  push:
    branches:
      - km-main-change
      #- main

jobs:
  Compare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dmmulroy/better-ts-errors.nvim
      uses: actions/checkout@v3
      # with:
      #   repository: dmmulroy/better-ts-errors.nvim
      #   path: better_ts_errors/
      #   ref: km-main-change #main <- change back before push to prod

    - name: Clone ts-error-translator repository
      run: git clone https://github.com/mattpocock/ts-error-translator.git ts_error_translator/

    - name: List contents of error_templates/ and errors
      run: |
        ls better_ts_errors/error_templates
        ls ts_error_translator/packages/engine/errors/

    - name: Compare Directories and Create PR
      run: |
        repository="dmmurloy/better-ts-errors.nvim"
        dir1="ts_error_translator/packages/engine/errors/"
        dir2="better_ts_errors/error_templates"

        differences=$(diff -rq "$dir1" "$dir2" || true)

        if [ -n "$differences" ]; then
          branch_name="auto-pr-$(date +%s)"
          git checkout -b "$branch_name"
          git add -A
          git commit -m "Auto commit for directory sync"
          git push origin "$branch_name"

          pull_request_title="Auto PR: Directory Sync"
          pull_request_body="Differences found between directories: $dir1 and $dir2\n\n$differences"
          pull_request_head="$branch_name"
          pull_request_base="main"

          response=$(curl -s -X POST "https://api.github.com/repos/$repository/pulls" -H "Authorization: token $GITHUB_TOKEN" -d '{
            "title": "'"${pull_request_title}"'",
            "body": "'"${pull_request_body}"'",
            "head": "'"${pull_request_head}"'",
            "base": "'"${pull_request_base}"'"
          }')

          echo "Pull request created": $pull_request_url""
        else
          echo "No differences found in directories."
        fi