name: Compare Directories

on:
  push:
    branches:
      - km-main-change
      #- main

jobs:
   Compare-Directories:
    runs-on: ubuntu-latest
    steps:
    - name: Clone dmmulroy/better-ts-errors.nvim
      run: git clone https://github.com/dmmulroy/better-ts-errors.nvim.git

    - name: Clone mattpocock/ts-error-translator repository
      run: git clone https://github.com/mattpocock/ts-error-translator.git

    - name: run config git
      run: |
        git config --global user.email "email@test.com"
        git config --global user.name "kylemelvin95"

    - name: Run diff script and create PR
      run: |
        # Define your directories and GitHub token here
        dir1="ts-error-translator/packages/engine/errors/"
        dir2="better-ts-errors.nvim/error_templates"

        # Use diff to compare the directories and store the differences in a variable
        differences=$(diff -rq $dir1 $dir2 || true)

        if [ -n "$differences" ]; then
          cd better-ts-errors.nvim/
          # Create a new branch and commit the changes
          branch_name="auto-pr-$(date +”%d-%b-%Y”)"
          git checkout -b "$branch_name"
          echo $differences > differences.patch
          git add differences.patch
          git commit -m "Auto commit for directory differences"
          git push origin "$branch_name"
        fi

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}  
        #   # Create a new pull request using the GitHub API
        #   curl -X POST "https://api.github.com/repos/dmmulroy/better-ts-errors.nvim/pulls" -H ${{ secrets.GITHUB_TOKEN }} -d '{
        #     "title": "Auto PR: Directory Differences",
        #     "body": "Differences found between directories: '"$dir1"' and '"$dir2"'\n\n'"$differences"'",
        #     "head": "'"$branch_name"'",
        #     "base": "main"
        #   }'
        # fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
