name: Compare Directories

on:
  push:
    branches:
      - km-main-change
      #- main

jobs:
  Compare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dmmulroy/better-ts-errors.nvim
      uses: actions/checkout@v3
      with:
        repository: dmmulroy/better-ts-errors.nvim
        path: better_ts_errors/
        ref: km-main-change #main <- change back before push to prod

    - name: Clone ts-error-translator repository
      run: git clone https://github.com/mattpocock/ts-error-translator.git ts_error_translator/

    - name: List contents of error_templates/ and errors
      run: |
        ls better_ts_errors/error_templates
        ls ts_error_translator/packages/engine/errors/
    

