name: Compare Directories

on:
  push:
    branches:
      - km-main-change
      #- main

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dmmulroy/better-ts-errors.nvim
      uses: actions/checkout@v3
      with:
        repository: dmmulroy/better-ts-errors.nvim
        path: error_templates/
        ref: km-main-change #main <- change back before push to prod

    # - name: Clone and checkout remote repository
    #   run: |
    #     git clone https://github.com/mattpocock/ts-error-translator.git
    #     cd ts-error-translator
    #     git checkout main
    #     cd packages/engine/errors
    #   working-directory: ${{ github.workspace }}

    # - name: Run the diff
    #   run: |
    #     diff -r packages/engine/errors ${{ github.workspace }}/error_templates
    #   working-directory: ${{ github.workspace }}/ts-error-translator
