name: Compare Directories

on:
  push:
    branches:
      - km-main-change
      #- main

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dmmulroy/better-ts-errors.nvim
      uses: actions/checkout@v3
      with:
        repository: dmmulroy/better-ts-errors.nvim
        path: error_templates
        ref: km-main-change #main <- change back before push to prod

    - name: Checkout mattpocock/ts-error-translator
      uses: actions/checkout@v3
      with:
        repository: mattpocock/ts-error-translator
        path: errors
        ref: main

    - name: Run the diff
      run: |
        diff -r error_templates errors
