name: Compare Directories

on:
  push:
    branches:
      - km-main-change
      #- main

jobs:
  Compare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dmmulroy/better-ts-errors.nvim
      uses: actions/checkout@v3
      with:
        repository: dmmulroy/better-ts-errors.nvim
        path: better_ts_errors/
        ref: km-main-change #main <- change back before push to prod

    - name: Clone ts-error-translator repository
      run: git clone https://github.com/mattpocock/ts-error-translator.git ts_error_translator/

    - name: List contents of error_templates/ and errors
      run: |
        ls better_ts_errors/error_templates
        ls ts_error_translator/packages/engine/errors/

    - name: Compare Directories and Create PR
      run: |
        dir1="better_ts_errors/error_templates"
        dir2="ts_error_translator/packages/engine/errors/"

        # Use diff to compare the directories and display the differences directly
        differences=$(diff -rq "$dir1" "$dir2")

        # Check the exit code of diff (0 if no differences, 1 if differences found)
        if [ $? -eq 0 ]; then
          echo "No differences found."
        else
          echo "Differences found:"
          echo "$differences"

          # Create a branch and push the changes
          git checkout -b branch-for-differences
          git add .
          git commit -m "Differences found"
          git push origin branch-for-differences

          # Create a pull request
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d '{
            "title": "Differences Found",
            "head": "branch-for-differences",
            "base": "main",  # Adjust the target branch as needed
            "body": "Differences were found between directories.",
            "maintainer_can_modify": true
          }' "https://api.github.com/repos/dmmulroy/better-ts-errors.nvim/pulls"
          
          exit 1  # Fail the workflow
        fi


